version: 2.1

aliases:
  - &workspace_root ~/dashkiosk
  - &persist_to_workspace
    root: *workspace_root
    paths:
      - entrypoint.sh
      - Dockerfile
  - &attach_workspace
     at: *workspace_root

orbs:
  docker-image: t3n/docker-image@1.0
  docker: circleci/docker@0.5.13

jobs:
  test:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:10
    steps:
      - checkout
  docker_build_and_push:
    working_directory: *workspace_root
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          registry: quay.io/t3n/dashkiosk

workflows:
  version: 2
  build_and_push:
    jobs:
      - docker_build_and_push:
          filters:
            branches:
              only:
                - master
          context: google
